// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yfNy435iopvVCdfX2MQrPHXJ-QpjhRk',
    appId: '1:955052202600:web:c482b437174c4ebc83f9dd',
    messagingSenderId: '955052202600',
    projectId: 'instgram-f9763',
    authDomain: 'instgram-f9763.firebaseapp.com',
    storageBucket: 'instgram-f9763.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLTEoCz2XW4nGQHph9BY1OLPwHzNzFPg',
    appId: '1:955052202600:android:05202b8038cbbec583f9dd',
    messagingSenderId: '955052202600',
    projectId: 'instgram-f9763',
    storageBucket: 'instgram-f9763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfnO0EozhKDarJE02Z5gOBB3-C4Hxlns',
    appId: '1:955052202600:ios:ae1e7e48f28f771d83f9dd',
    messagingSenderId: '955052202600',
    projectId: 'instgram-f9763',
    storageBucket: 'instgram-f9763.appspot.com',
    iosClientId: '955052202600-tjtkjqg195jns6u2sbo9tlns9j6kke8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
